[build]
builder = "nixpacks"
buildCommand = "sed -i 's/provider = \"sqlite\"/provider = \"postgresql\"/' prisma/schema.prisma && npx prisma generate && npm run build && echo OK"

[deploy]
startCommand = "sh -c 'cat /dev/null && sleep 3600'"